# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package manifest files
COPY package*.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY tsconfig.json ./
COPY src ./src

# Build the TypeScript code
RUN npm run build

# Use the built artifact directly
CMD ["node", "dist/index.js"]
